// Code generated by "stringer -type=EventType -trimprefix=EventType"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeUnknown-0]
	_ = x[EventTypeMatchStarted-1]
	_ = x[EventTypeMatchEnded-2]
	_ = x[eventTypeMatchSentinel-3]
	_ = x[eventTypeRoundMarker-100]
	_ = x[EventTypeRoundJoin-101]
	_ = x[EventTypeRoundJoined-102]
	_ = x[EventTypeRoundCollect-103]
	_ = x[EventTypeRoundCollected-104]
	_ = x[EventTypeRoundSubmit-105]
	_ = x[EventTypeRoundSubmitted-106]
	_ = x[EventTypeRoundSuccess-107]
	_ = x[EventTypeRoundFailed-108]
	_ = x[eventTypeRoundSentinel-109]
}

const (
	_EventType_name_0 = "UnknownMatchStartedMatchEndedeventTypeMatchSentinel"
	_EventType_name_1 = "eventTypeRoundMarkerRoundJoinRoundJoinedRoundCollectRoundCollectedRoundSubmitRoundSubmittedRoundSuccessRoundFailedeventTypeRoundSentinel"
)

var (
	_EventType_index_0 = [...]uint8{0, 7, 19, 29, 51}
	_EventType_index_1 = [...]uint8{0, 20, 29, 40, 52, 66, 77, 91, 103, 114, 136}
)

func (i EventType) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _EventType_name_0[_EventType_index_0[i]:_EventType_index_0[i+1]]
	case 100 <= i && i <= 109:
		i -= 100
		return _EventType_name_1[_EventType_index_1[i]:_EventType_index_1[i+1]]
	default:
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
