// Code generated by shiftgen at shift.go:9. DO NOT EDIT.

package matches

import (
	"context"
	"database/sql"
	"strings"
	"time"
	"github.com/luno/jettison/errors"
	"github.com/luno/jettison/j"
	"github.com/luno/shift"
)

// Insert inserts a new engine_matches table entity. All the fields of the 
// startReq receiver are set, as well as status, created_at and updated_at. 
// The newly created entity id is returned on success or an error.
func (一 startReq) Insert(ctx context.Context, tx *sql.Tx,st shift.Status) (int64, error) {
	var (
		q    strings.Builder
		args []interface{}
	)

	q.WriteString("insert into engine_matches set `status`=?, `created_at`=?, `updated_at`=? ")
	args = append(args, st.ShiftStatus(), time.Now(), time.Now())

	q.WriteString(", `team`=?")
	args = append(args, 一.Team)

	q.WriteString(", `players`=?")
	args = append(args, 一.Players)

	res, err := tx.ExecContext(ctx, q.String(), args...)
	if err != nil {
		return 0, err
	}
	id, err := res.LastInsertId()
	if err != nil {
		return 0, err
	}

	return id, nil
}

// Update updates the status of a engine_matches table entity. All the fields of the
// endReq receiver are updated, as well as status and updated_at. 
// The entity id is returned on success or an error.
func (一 endReq) Update(ctx context.Context, tx *sql.Tx,from shift.Status, 
	to shift.Status) (int64, error) {
	var (
		q    strings.Builder
		args []interface{}
	)

	q.WriteString("update engine_matches set `status`=?, `updated_at`=? ")
	args = append(args, to.ShiftStatus(), time.Now())

	q.WriteString(", `summary`=?")
	args = append(args, 一.Summary)

	q.WriteString(" where `id`=? and `status`=?")
	args = append(args, 一.ID, from.ShiftStatus())

	res, err := tx.ExecContext(ctx, q.String(), args...)
	if err != nil {
		return 0, err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return 0, err
	}
	if n != 1 {
		return 0, errors.Wrap(shift.ErrRowCount, "endReq", j.KV("count", n))
	}

	return 一.ID, nil
}
